---
title: "Individual-based models using R:"
subtitle: "Encapsulated object-oriented programming with R6"
author: "Alexandre Courtiol, Liam D Bailey, Colin Vullioud, Elisa Donati, Mathias Franz?, Ilja Heckmann?, Viktoriia Radchuk?, Stephanie Kramer-Schadt?, Olivia Judson?, Wiston Chang?, Olivier Gimenez?, François Rousset?"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Individual-based models and encapsulated object-oriented programming

Individual-based models (IBM) are increasingly used in ecology and evolution [REF]. They allow for the study of the emergent properties of a system that are often too complex to be mathematically tractable. For example, they have been used to XX, XX, and XX [give good examples].

*Object-Oriented Programming* (OOP), sometimes called more precisely *Encapsulated Object-Oriented Programming* (EOOP), is arguably the most suitable programming paradigm for a straightforward implementation of IBM [REF]. This paradigm consists in the development of computer code organised in *objects* and *classes*. An object is a virtual structure that contains data organised in a specified way. Developers impose such specifications by defining *classes* -- the blue print for all possible objects sharing the same structure. For example, if we imaging a class called `individual`, a first instance of that class could be an object containing a field called `name` with value `"John Doe"`, a field called `sex` with value `"male"`, and a field called `age` with a value `37`. A second instance of the same class could be an object containing the values `"Jane Smith"`, `"female"` and `45` for the respective fields.

The word *encapsulated* in EOOP implies that the object of a given class can also store *methods* which contains the code necessary for accessing, adding, removing, or modifying values within objects. For example, in the previous class we can imagine a field named `birthday` that would contain a method necessary to update field `age`: each call of `birthday` would increase the age by one year for the individual.

EOOP is convenient for the implementation of IBM for two main reasons. First and foremost, EOOP allows for drawing a parallel between the computer code being developed and the structure of the biological problem one studies. Below, we will focus on a simple example inspired from the textbook example of the evolution of colouration in the peppered moth (*Biston betularia*). You will see that we can define a class *individual* for representing the individual moths, a class *population* for representing the biological population of moths, and a class *world* which represents the environment in which the population evolves. The content of objects directly follows. For example, all instances of the class individuals will have a field `colour` referring to their colour and a field `status` referring to their survival status (alive or dead), `population` will contain a field `invididuals` to strore all the individuals, and `world` will contain information about the colour of the trees in the environment.

The parallel between the modularity of the computer code and of the biology greatly facilitate the conception of such simulations. Indeed, the programmer can, to a large extent, make abstraction of the internal data structure when developing code. For example, if one wanted to consider that moths can be of two sexes (we will not do so here), one would have to add a field in the class individual to store the sex, and define new methods for handling the sex specific behaviour at the level of the population. During this process, one would not have to worry about any other characteristics of the class `individual` (or other classes) unless the biology dictates otherwise.

The second key benefit of EOOP in the context of IBM is that objects are *mutable*: their content can change without having to create new objects. This property is related to the presence of encapsulated methods since an important role of methods is precisely to modify the content of objects. In practical terms, it implies that the values of the characteristics of objects can change without increasing the memory footprint of the objects. In the context of IBM, it means that individuals can develop and that population can evolve during the simulation without risking memory requirement to grow substantially.

One alternative to EOOP which many ecologists and evolutionary biologists are familiar with is *functional programming* (FP): a programming paradigm in which the workflow consists in a sequence of function calls producing new objects. While such programming paradigm can still be based on objects (as in R), each function call creates a new object. In general, objects used in functional programming are immutable. Therefore, functions that seem to modify objects property often merely create a copy of the original object with the updated property. This copy may possibly be accessed using the same name as the original object, but the reference actually point to a different location in the physical memory of the computer. The issue with a FP implementation of an IBM is thus that the computer spends a great amount of time and memory reproducing the same content in different memory location. For example, calling a function `birthday` implemented using FP would, on top of computing the new age, result in duplicating the name and sex of the individuals in computer memory.


## Object-oriented programming in R

Since the vast majority of young ecologists and evolutionary biologists are familiar with the statistical software and programming language R, we could expect many people to rely on R for implementing IBM. This does not however seem to be the case. Researchers in ecology and evolution tend to rely instead on lower level languages with EOOP possibilities such as C++ or Java to implement their IBM [e.g. REF], on software that have been specifically developed to program IBM based on such languages (e.g. NetLogo) [e.g. REF], or on Python [e.g. REF] -- a general-purpose programming language that is widely used in other fields but not so much in ecology and evolution. [Some quantitative statement would be more convincing... perhaps we should pick a couple of journals in which IBM tend to be published and due a small quantitative study.]

Having to learn a new language such as C++, Java or even Python, is for many a daunting task. Relying on platforms dedicated to IBM such as NetLogo is an effective alternative, which we do not want to reject. Yet, using such alternatives still requires the user to grow a completely new vocabulary and learn a new set of tools (even when R interfaces have been developped for such alternatives). Moreover, such platforms do not offer the full flexibility and transparency than what the experience of building an IBM from the ground up. We will come back on the pros and cons of using the methodology we propose here versus its alternatives in discussion.

So why do very few people rely on R for programming IBM despite many already using R proficently? Our guess is that most people are not aware of the EOOP functionalities offered by R. Indeed, although everything you can create in an R console is an object [REF Chambers], the dominant type of OOP systems in R have been conceived with FP in mind.

While the FP paradigm is particularly well suited for data analysis, it is not ideal for IBM. Indeed, the usual system of object that most users are familiar with -- the *S3* object system -- provides classes are not particular well designed for IBM: `data.frame` and `list` are immutable, and `environemnt` are notoriously difficult to manipulate. An alternative to the *S3* object system, called *S4* is also available in R since version 1.4 (released end of 2001). While this development brought to R some key functionalities found in alternative OOP languages (e.g. multiple inheritance and multiple dispatch) and the possibility to define classes with a structure that would be suitable for IBM, the *S4* system is not particularly useful for IBM. It is indeed still rooted in FP and thus generates objects that are not generally mutable. Moreover, by bringing rigour to the definition of classes, *S4* brought with it much of the complexity that R user like to avoid and despite being strongly championned by some of **R** (and **S**) pionneers, *S4* did not become very popular and remains to this date seldom used beyond a few well known exceptions (the **bioconductor** environment and the package **Matrix** and some of the package drawing heavily from it).

[HERE]


From R version 2.12 (October 2010) [info from sideshow by Chambers], yet another object system was added to core R. This new system was officially called *Reference Classes* and sometimes referred to informally as *RC* or *R5*. Although the *RC* object system is built around *S4*, it does differ considerably from it. The *RC* object system was and remains the only supported *encapsulated* OOP in R. Like alternative friendly programming language to conceive IBM, *RC* thus allows for the encapsulation of methods/function in classes, which means that methods acting on the data stored in a given object are stored in that object too.

Encapsulated OOP is particularly useful for dealing with object that changes through time. The reason is that such type of OOP allows for objects to be mutated in place. In functional OOP, objects are not designed to be modified: each function generate a new output and stores it anew (even if the name given to such object is sometimes that of an existing one). [Need to clarify this important distinction from the onset] 

One important aspect of R various object systems is that whether you rely on *S4*, *RC*, *R6* or other less known systems, you can always program all methods and data components in such classes using the system *S3* with which every R user is (even if not always conscientiously) familiar with.

## R6 [check vignette!]

Like *RC*, *R6* is an encapsulated OOP: the objects can contain both data and methods and the object are mutable (unlike *S3* [not sure about *S4*]). *R6* offers several benefits compared to *RC* without introducing a priori particular drawbacks. The two main ones are that the memory footprint and the speed at which instances of classes are created and field reads from them is much faster. For many usages, the costs in terms of memory and computation speed are not determinant but for IBM it is. Indeed, if one needs to create say thousands instances of the class individual to simulate a big population, relying on the heavy instances of *RC* may become problematic.

*R6* also introduces the concept of private properties common to OOP outside R, and it allows for robust inheritance across packages. The later properties is particularly interesting in the context of the development of general IBM platform, since it implies that independent packages could implement their own classes based on those offered by the platform.

Although *R6* is not very well known, it happens to be installed on the computer of most R users and developers since it is used internally to handle particular objects in a few packages that are extremely popular such as **dplyr** [used for DataMask; switch from *RC* to *R6* in version 0.3], **shiny**, **roxygen2** or **testthat** [note: also used in nimble]. 



Like in Java and C++, you can both define public and private fields (i.e. not accessible from the outside), it supports inheritance (where you can add or override methods), initializer methods (i.e. constructor).

Technically, *R6* objects are just environments with a particular structure.


## Biological example

## Implementation using R6

## Implementation using S3

## Performances

## Comparison to NetLogo
